const ACTION_TYPES = {
	ERROR: 'ERROR',
	GET_USER_SIGNUP_DATA: 'GET_USER_SIGNUP_DATA',
	REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS',
	GET_LOGIN_DATA: 'GET_LOGIN_DATA',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	SAVE_ALL_QUESTIONS: 'SAVE_ALL_QUESTIONS',
	SAVE_ALL_ANSWERS: 'SAVE_ALL_ANSWERS'
};

export default ACTION_TYPES;
